### ISSUE TITLE
Feedback on week 11 project progress for CS2113-T14-1

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113-T14-1/main#267]
## Team progress for `v1.3`
* Milestone `v1.3` properly managed:
   * [x] A suitable deadline 2019-10-30 set(:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
* [x] New JAR released on GitHub in the last 7 days (:heavy_check_mark: well done!)
* [x] `Ui.png` has been updated in the last 7 days (:heavy_check_mark: well done!)
* Milestones setup:
   * [x] Milestone `v1.3` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
## Individual progress of @aquohn for`v1.3`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks(:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.3` milestone https://github.com/AY1920S1-CS2113-T14-1/main/issues/215 https://github.com/AY1920S1-CS2113-T14-1/main/issues/213 https://github.com/AY1920S1-CS2113-T14-1/main/issues/212 https://github.com/AY1920S1-CS2113-T14-1/main/issues/211 https://github.com/AY1920S1-CS2113-T14-1/main/issues/210 https://github.com/AY1920S1-CS2113-T14-1/main/issues/209 https://github.com/AY1920S1-CS2113-T14-1/main/issues/208 https://github.com/AY1920S1-CS2113-T14-1/main/issues/207 https://github.com/AY1920S1-CS2113-T14-1/main/issues/206 https://github.com/AY1920S1-CS2113-T14-1/main/issues/203 https://github.com/AY1920S1-CS2113-T14-1/main/issues/150 https://github.com/AY1920S1-CS2113-T14-1/main/issues/144 https://github.com/AY1920S1-CS2113-T14-1/main/issues/74 (:heavy_check_mark: well done!)
* [not graded] Ensured the code is [RepoSense  compatible](https://nuscs2113-ay1920s1.github.io/website/admin/project-w10-mid-v13.html) and your code contributions are showing code correctly (:question: tick this yourself after completing the item)
## Individual progress of @jeremykwok for`v1.3`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks(:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.3` milestone https://github.com/AY1920S1-CS2113-T14-1/main/issues/224 https://github.com/AY1920S1-CS2113-T14-1/main/issues/202 https://github.com/AY1920S1-CS2113-T14-1/main/issues/191 https://github.com/AY1920S1-CS2113-T14-1/main/issues/185 https://github.com/AY1920S1-CS2113-T14-1/main/issues/172 https://github.com/AY1920S1-CS2113-T14-1/main/issues/171 https://github.com/AY1920S1-CS2113-T14-1/main/issues/150 https://github.com/AY1920S1-CS2113-T14-1/main/issues/144 https://github.com/AY1920S1-CS2113-T14-1/main/issues/115 (:heavy_check_mark: well done!)
* [not graded] Ensured the code is [RepoSense  compatible](https://nuscs2113-ay1920s1.github.io/website/admin/project-w10-mid-v13.html) and your code contributions are showing code correctly (:question: tick this yourself after completing the item)
## Individual progress of @gowgos5 for`v1.3`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks(:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.3` milestone https://github.com/AY1920S1-CS2113-T14-1/main/pull/245 https://github.com/AY1920S1-CS2113-T14-1/main/pull/169 https://github.com/AY1920S1-CS2113-T14-1/main/pull/245 https://github.com/AY1920S1-CS2113-T14-1/main/issues/237 https://github.com/AY1920S1-CS2113-T14-1/main/issues/216 https://github.com/AY1920S1-CS2113-T14-1/main/issues/190 https://github.com/AY1920S1-CS2113-T14-1/main/issues/189 https://github.com/AY1920S1-CS2113-T14-1/main/issues/187 https://github.com/AY1920S1-CS2113-T14-1/main/issues/170 https://github.com/AY1920S1-CS2113-T14-1/main/pull/169 https://github.com/AY1920S1-CS2113-T14-1/main/issues/150 https://github.com/AY1920S1-CS2113-T14-1/main/issues/146 https://github.com/AY1920S1-CS2113-T14-1/main/issues/145 https://github.com/AY1920S1-CS2113-T14-1/main/issues/144 https://github.com/AY1920S1-CS2113-T14-1/main/issues/102 https://github.com/AY1920S1-CS2113-T14-1/main/issues/30 (:heavy_check_mark: well done!)
* [not graded] Ensured the code is [RepoSense  compatible](https://nuscs2113-ay1920s1.github.io/website/admin/project-w10-mid-v13.html) and your code contributions are showing code correctly (:question: tick this yourself after completing the item)
## Individual progress of @jacobtoresson for`v1.3`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks(:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.3` milestone https://github.com/AY1920S1-CS2113-T14-1/main/issues/202 https://github.com/AY1920S1-CS2113-T14-1/main/issues/193 https://github.com/AY1920S1-CS2113-T14-1/main/issues/192 https://github.com/AY1920S1-CS2113-T14-1/main/issues/150 https://github.com/AY1920S1-CS2113-T14-1/main/issues/144 https://github.com/AY1920S1-CS2113-T14-1/main/issues/143 https://github.com/AY1920S1-CS2113-T14-1/main/issues/119 https://github.com/AY1920S1-CS2113-T14-1/main/issues/115 https://github.com/AY1920S1-CS2113-T14-1/main/issues/84 https://github.com/AY1920S1-CS2113-T14-1/main/issues/83 (:heavy_check_mark: well done!)
* [not graded] Ensured the code is [RepoSense  compatible](https://nuscs2113-ay1920s1.github.io/website/admin/project-w10-mid-v13.html) and your code contributions are showing code correctly (:question: tick this yourself after completing the item)

Tutor: @sanjukta99

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-10-31 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
