### ISSUE TITLE
As a house officer who has to manage a lot of information...

### ISSUE THREAD

**Issue by gowgos5** [AY1920S1-CS2113-T14-1/main#32]
- [ ] #33 - Search through all the records of a patient
- [ ] #34 - Flag and view the critical issues to follow up for each patient
- [ ] #35 - Easily view and navigate through data associated with particular conditions that particular patients have
- [ ] #47 - Easily link new information and follow-up items to particular conditions

**Comment by gowgos5** [comment]
Reorganising type.Epic.
