### ISSUE TITLE
As a house officer who needs to quickly input a lot of data and is prone to mistyping...

### ISSUE THREAD

**Issue by gowgos5** [AY1920S1-CS2113-T14-1/main#40]
- [ ] #39 - Can make typing errors but still have my input recognised
- [ ] #41 - Confirm my input type and modify it quickly if it is incorrect
- [ ] #42 - Undo my previous commands
- [ ] #43 - Have my input automatically checked to ensure it is of the right format

**Comment by gowgos5** [comment]
Reorganising type.Epic.
