### ISSUE TITLE
As a house officer in a hurry, I can quickly access the relevant data of the patient I am seeing.

### ISSUE THREAD

**Issue by aquohn** [AY1920S1-CS2113-T14-1/main#48]
- [ ] #37 View previous medical history: view investigation results, courses of medicine completed, general notes on medical history, completed plan items
- [ ] #35 View and navigate data associated with each condition: go from viewing the impression to a detailed view of some evidence or treatment, and vice versa
- [ ] #30 Check allergies: display allergies and other vital data on patient's main page, and maybe in a little box at the side even when viewing/entering other kinds of data
- [ ] #33 Search for relevant data: search through treatments/evidence for a string?
