### ISSUE TITLE
As a house officer who needs to quickly input a lot of data and is prone to mistyping, I can make mistakes when typing commands but still have them accepted.

### ISSUE THREAD

**Issue by aquohn** [AY1920S1-CS2113-T14-1/main#49]
- [ ] #43 Format checks for fields like dates, and values like medicine names
- [ ] #42 Undo previous commands
- [ ] #39 Autocorrect for commands
- [ ] #41 Confirmation for autocorrect, and option to edit input if autocorrect has not parsed user's intention correctly
